#!/bin/bash

set -e

temp_dir=$(mktemp -d)
tawk_dir="${temp_dir}/tawkto"

cp -r ./ "${tawk_dir}"

rm "${tawk_dir}/tawkto.zip" || /bin/true
rm "${tawk_dir}/package_prestashop"
rm -rf "${tawk_dir}/.git"
rm "${tawk_dir}/.gitignore"

pushd "${temp_dir}"
zip -r tawkto.zip tawkto
popd

cp "${temp_dir}/tawkto.zip" .

rm -r "${temp_dir}"
