version: '3.8'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: prestashop
      MYSQL_DATABASE: prestashop
      MYSQL_USER: prestashop
      MYSQL_PASSWORD: prestashop

  web:
    depends_on:
      - db
    image: prestashop/prestashop:${PRESTASHOP_IMAGE_VERSION}
    ports:
      - 8000:80
    volumes:
      - web_data:/var/www/html
      - type: bind
        source: ${PRESTASHOP_DIR}
        target: /var/www/html/modules/tawkto
    links:
      - db
    environment:
      DB_SERVER: db
      DB_USER: prestashop
      DB_PASSWD: prestashop
      DB_NAME: prestashop
      PS_INSTALL_AUTO: 1
      PS_FOLDER_ADMIN: admin_ps
      PS_FOLDER_INSTALL: install_ps
      PS_DOMAIN: localhost:8000
      ADMIN_MAIL: admin@example.com
      ADMIN_PASSWD: adminps123

volumes:
  db_data:
  web_data:
