version: '3.8'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: prestashop
      MYSQL_DATABASE: prestashop
      MYSQL_USER: prestashop
      MYSQL_PASSWORD: prestashop

  web:
    build:
      context: .
      args:
        PRESTASHOP_IMAGE_VERSION: ${PRESTASHOP_IMAGE_VERSION}
        DB_SERVER_ARG: db
        DB_USER_ARG: prestashop
        DB_PASSWD_ARG: prestashop
        DB_NAME_ARG: prestashop
        PS_INSTALL_AUTO_ARG: 1
        PS_FOLDER_ADMIN_ARG: admin_ps
        PS_FOLDER_INSTALL_ARG: install_ps
        PS_DOMAIN_ARG: localhost:8000
        ADMIN_MAIL_ARG: admin@example.com
        ADMIN_PASSWD_ARG: adminps
    depends_on:
      - db
    ports:
       - 8000:80
    volumes:
      - web_data:/var/www/html
    links:
      - db

volumes:
  db_data:
  web_data:
